-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Lure CASCADE;
DROP TABLE IF EXISTS Spot CASCADE;
DROP TABLE IF EXISTS Species CASCADE;
DROP TABLE IF EXISTS Trip CASCADE;
DROP TABLE IF EXISTS Fish CASCADE;
